#!/usr/bin/env python3
import json
from pathlib import Path

COLLECTED_AT = "2026-05-23T18:00:00Z"
FW = "1.0.0"
OUT = Path(__file__).resolve().parent.parent / "data" / "ideas"

def src(url, title, grade, signal, quote=None):
    s = {"url": url, "title": title, "accessedAt": COLLECTED_AT, "grade": grade, "signalType": signal}
    if quote:
        s["quote"] = quote
    return s

def gates(g1, g2, g3, g4, g5):
    return {
        "g1_montrealAnchor": {"passed": True, "notes": g1},
        "g2_sevenDayShip": {"passed": True, "notes": g2},
        "g3_cashPath": {"passed": True, "notes": g3},
        "g4_soloOps": {"passed": True, "notes": g4},
        "g5_legal": {"passed": True, "notes": g5},
        "allPassed": True,
    }

IDEAS = [
    {
        "id": "plateau-freelancer-tax-reserve",
        "title": "Plateau Freelancer Tax Reserve Calculator",
        "tagline": "QST/GST and Revenu Québec instalment planner for Mile End creatives.",
        "category": "b2b-micro-saas",
        "jtbd": {
            "situation": "When April 30 tax balance is due but return deadline is June 15",
            "persona": "Mile End freelance designer with fluctuating income",
            "motivation": "set aside correct QST/GST and provincial tax each month",
            "outcome": "avoid shock tax bill and Revenu Québec penalties",
            "statement": "When freelancing in Mile End, a designer wants monthly tax reserve calculations so they avoid April tax shock.",
        },
        "montrealAngle": "Plateau/Mile End freelancer density; Quebec TP-80 filing + QST $30K threshold + April 30 balance vs June 15 filing unique to QC.",
        "whyNow": "TVA Nouvelles May 2026 article on freelancer tax bill shock; electronic payment rules tightened 2024.",
        "persona": {"name": "Freelance creative/consultant, sole proprietor", "borough": "Le Plateau-Mont-Royal", "language": "bilingual", "estimatedCount": 15000, "countSource": "[hypothesis] Montreal self-employed per StatCan [verify]"},
        "competitors": [{"name": "Accountant annual filing", "montrealPresence": "strong", "notes": "$500-1500/yr; not monthly reserve tool."}, {"name": "Wave/QBO", "montrealPresence": "strong", "notes": "General accounting; weak QST instalment UX for solos."}],
        "mvpScope": {
            "coreJob": "Input monthly revenue/expenses, output QC tax reserve amount",
            "mustHave": ["Monthly revenue input", "QST/GST threshold alert", "Reserve recommendation", "Email monthly reminder", "FR UI"],
            "wontHave": ["TP-1 filing", "Receipt OCR", "Multi-entity"],
            "stack": ["Next.js", "Supabase", "Resend", "Stripe"],
            "buildDays": 6,
            "conciergeFallback": "Spreadsheet template sold for $29",
        },
        "businessModel": {"pricingCAD": "$12/mo or $99/yr", "firstCustomer": "Montreal Entrepreneurs Collective member", "revenue60Day": {"low": 600, "high": 3000}},
        "gtm": {"firstTenCustomers": ["Meetup MEC", "r/QuebecEntreprise", "CPA referral for overflow clients"], "channels": ["Meetup", "Reddit", "CPA"]},
        "assumptions": [{"statement": "Freelancers pay $12/mo for reserve alerts", "confidence": "hypothesis", "testMethod": "Free Jan-Mar pilot, convert in April"}],
        "sources": [
            src("https://www.tvanouvelles.ca/2026/05/14/facture-fiscale--un-gouffre-financier-pour-les-travailleurs-autonomes", "TVA Nouvelles freelancer tax shock", "B", "pain-verified"),
            src("https://www.revenuquebec.ca/fr/citoyens/travailleurs-autonomes/particularites-du-travailleur-autonome/", "Revenu Québec travailleurs autonomes", "A", "regulatory"),
            src("https://justepourtous.revenuquebec.ca/en/profiles/self-employed-workers", "Revenu Québec self-employed guide", "A", "regulatory"),
        ],
        "gates": gates("Quebec tax calendar unique; Mile End freelancer cluster.", "Calculator + reminders = 6 days.", "50 subs at $12/mo by day 60.", "Self-serve.", "Not tax advice; disclaimer + CPA referral."),
        "status": "collected",
    },
    {
        "id": "resto-tfw-francization-kit",
        "title": "Resto TFW Francization Kit",
        "tagline": "French workplace onboarding templates for Montreal restaurants hiring temporary foreign workers.",
        "category": "compliance-regtech",
        "jtbd": {
            "situation": "When ARQ asks Francisation Québec for restaurant-specific TFW workplace programs",
            "persona": "Owner of Caribbean restaurant in Old Port with 20% TFW staff",
            "motivation": "deploy French onboarding materials and track employee progress",
            "outcome": "retain TFW staff while meeting francization expectations",
            "statement": "When hiring TFW kitchen staff, an Old Port owner wants French onboarding kits so they retain workers and meet francization norms.",
        },
        "montrealAngle": "ARQ brief explicitly calls for Francisation Québec workplace programs for restaurant TFWs; Old Port restaurants like Kwizinn depend on TFW stability.",
        "whyNow": "Oct 2025 TFW cap crisis + ARQ francization ask in National Assembly brief.",
        "persona": {"name": "Restaurant owner with TFW hires", "borough": "Ville-Marie", "language": "bilingual", "estimatedCount": 400, "countSource": "[hypothesis] Montreal restaurants with TFW >10%"},
        "competitors": [{"name": "Francisation Québec", "url": "https://www.quebec.ca/", "montrealPresence": "strong", "notes": "Generic programs; not restaurant-shift specific."}],
        "mvpScope": {
            "coreJob": "Download restaurant-role French phrase cards and onboarding checklists",
            "mustHave": ["Role-based FR phrase cards (PDF)", "Onboarding checklist", "Progress tracker", "Stripe $79 kit", "FR/EN manager UI"],
            "wontHave": ["Francisation Québec integration", "Certified translation", "HRIS"],
            "stack": ["Next.js", "Stripe", "React-PDF"],
            "buildDays": 5,
            "conciergeFallback": "PDF pack sold via Gumroad",
        },
        "businessModel": {"pricingCAD": "$79 kit + $29/mo tracker", "firstCustomer": "ARQ member restaurant Old Port", "revenue60Day": {"low": 1500, "high": 5000}},
        "gtm": {"firstTenCustomers": ["ARQ direct outreach", "Kwizinn-type owner intro", "Immigration consultant partners"], "channels": ["ARQ", "Partners"]},
        "assumptions": [{"statement": "Restaurants buy templated FR kits vs custom HR", "confidence": "hypothesis", "testMethod": "5 restaurant owner interviews"}],
        "sources": [
            src("https://montreal.citynews.ca/2025/10/02/temporary-workers-quebec-ottawa/", "CityNews ARQ TFW francization ask", "B", "regulatory"),
            src("https://montreal.citynews.ca/2025/10/05/quebec-restaurants-immigration-worker-cap/", "CityNews Kwizinn TFW reliance", "B", "pain-verified"),
        ],
        "gates": gates("Montreal restaurant TFW concentration + ARQ advocacy.", "PDF templates + tracker = 5 days.", "20-40 kit sales at $79.", "Digital product low support.", "Templates not certified legal/compliance docs."),
        "status": "collected",
    },
    {
        "id": "bill96-storefront-signage-check",
        "title": "Bill 96 Storefront Signage Checker",
        "tagline": "Photo audit tool for French predominant signage on Montreal retail storefronts.",
        "category": "compliance-regtech",
        "jtbd": {
            "situation": "When Bill 96 requires French markedly predominant on public signs from June 2025",
            "persona": "Owner of bilingual boutique on Sainte-Catherine in the Village",
            "motivation": "audit storefront signage before OQLF inspection",
            "outcome": "avoid $3000-30000/day fines",
            "statement": "When Bill 96 signage rules apply, a Village boutique owner wants a photo audit so they fix signs before fines.",
        },
        "montrealAngle": "Montreal retail corridors (Ste-Catherine, Mont-Royal) mix EN-heavy branding with Bill 96 predominant French rule; CBC documented business group panic.",
        "whyNow": "Rules effective June 1 2025; packaging/signage compliance still catching up May 2026.",
        "persona": {"name": "Independent retailer, 1-3 locations", "borough": "Ville-Marie", "language": "bilingual", "estimatedCount": 2000, "countSource": "[hypothesis] Montreal retail SMBs with EN branding"},
        "competitors": [{"name": "Signage fabricators", "montrealPresence": "strong", "notes": "Sell new signs; no audit SaaS."}, {"name": "OQLF guidance PDFs", "montrealPresence": "strong", "notes": "Free; not interactive."}],
        "mvpScope": {
            "coreJob": "Upload storefront photo, get checklist of Bill 96 signage fixes",
            "mustHave": ["Photo upload", "Rule-based checklist (not AI legal)", "Fix recommendations", "PDF report", "Stripe $59"],
            "wontHave": ["Automated OQLF compliance certification", "Sign design service"],
            "stack": ["Next.js", "Supabase Storage", "Stripe"],
            "buildDays": 6,
            "conciergeFallback": "Manual photo review for $59",
        },
        "businessModel": {"pricingCAD": "$59/audit; $149/3 locations", "firstCustomer": "SDC Village merchant", "revenue60Day": {"low": 1200, "high": 5000}},
        "gtm": {"firstTenCustomers": ["SDC du Village outreach", "Mont-Royal Ave merchant walk", "Signage company referral fees"], "channels": ["SDC", "Walk-in sales"]},
        "assumptions": [{"statement": "Retailers pay $59 for signage audit", "confidence": "hypothesis", "testMethod": "10 SDC merchant conversations"}],
        "sources": [
            src("https://www.cbc.ca/news/canada/montreal/bill-96-new-rules-french-signs-1.7549484", "CBC Bill 96 signage rules", "B", "regulatory", "Fines $3000-30000/day."),
            src("https://www.cfib-fcei.ca/en/site/qc-law-14-bill-96", "CFIB Bill 96 business impact", "B", "pain-verified"),
        ],
        "gates": gates("Montreal retail EN/French signage tension acute.", "Upload + checklist = 6 days.", "20-40 audits at $59.", "Manual review initially.", "Audit guidance not legal certification."),
        "status": "collected",
    },
    {
        "id": "mile-end-bilingual-invoice",
        "title": "Mile End Bilingual Invoice Generator",
        "tagline": "Bill 96-compliant FR-primary invoices for Quebec freelancers and creative SMBs.",
        "category": "b2b-micro-saas",
        "jtbd": {
            "situation": "When invoicing Quebec clients requires French at equal or greater prominence",
            "persona": "Mile End freelance videographer billing local agencies",
            "motivation": "generate compliant bilingual invoices with QST/GST lines",
            "outcome": "get paid faster without accountant invoice fixes",
            "statement": "When billing Quebec clients, a Mile End freelancer wants FR-primary invoices so they comply with Bill 96 contract rules.",
        },
        "montrealAngle": "Mile End creative freelancer cluster; Bill 96 consumer contract French requirement; many use English-only Stripe invoices.",
        "whyNow": "Bill 96 contract/warranty French rules in effect; freelancers already struggling with TP-80 complexity.",
        "persona": {"name": "Creative freelancer or 1-5 person studio", "borough": "Le Plateau-Mont-Royal", "language": "bilingual", "estimatedCount": 8000, "countSource": "[hypothesis] Montreal creative self-employed"},
        "competitors": [{"name": "QuickBooks/Wave", "montrealPresence": "strong", "notes": "Generic; Bill 96 French prominence not default."}, {"name": "Accountant-drafted templates", "montrealPresence": "strong", "notes": "One-time; not SaaS."}],
        "mvpScope": {
            "coreJob": "Create and email PDF invoice with French-primary layout and QST/GST",
            "mustHave": ["FR-primary invoice template", "QST/GST line items", "Client database", "PDF email send", "Stripe $15/mo"],
            "wontHave": ["Full accounting", "Bank sync", "Multi-currency"],
            "stack": ["Next.js", "Supabase", "React-PDF", "Stripe"],
            "buildDays": 7,
            "conciergeFallback": "Notion + PDF template for $29 one-time",
        },
        "businessModel": {"pricingCAD": "$15/mo or $149/yr", "firstCustomer": "Mile End coworking bulletin board", "revenue60Day": {"low": 500, "high": 2500}},
        "gtm": {"firstTenCustomers": ["Notman House board", "MEC meetup", "Creative agency referrals"], "channels": ["Coworking", "Meetup"]},
        "assumptions": [{"statement": "Creatives switch from Word templates for $15/mo", "confidence": "hypothesis", "testMethod": "Free trial with 20 Mile End freelancers"}],
        "sources": [
            src("https://educaloi.qc.ca/en/capsules/francization-rules-for-employers/", "Éducaloi Bill 96 consumer contracts", "A", "regulatory"),
            src("https://www.cbc.ca/news/canada/montreal/bill-96-new-rules-french-signs-1.7549484", "CBC Bill 96 business rules", "B", "regulatory"),
        ],
        "gates": gates("Montreal creative economy + Bill 96 contract rules.", "Invoice CRUD + PDF = 7 days.", "30-50 subs at $15/mo.", "Self-serve SaaS.", "Not accounting/tax advice."),
        "status": "collected",
    },
    {
        "id": "commercial-lease-renewal-workbook",
        "title": "Commercial Lease Renewal Workbook",
        "tagline": "Self-serve renewal prep for Ville-Émard and Monk Blvd merchants facing rent spikes.",
        "category": "property-real-estate",
        "jtbd": {
            "situation": "When commercial lease renewal arrives with no TAL protection",
            "persona": "Monk Blvd retail owner facing speculation-driven increase",
            "motivation": "document negotiation history and compare to neighborhood closures",
            "outcome": "make informed stay/leave decision before lease expiry",
            "statement": "When renewal arrives on Monk Blvd, a merchant wants a prep workbook so they negotiate from data not panic.",
        },
        "montrealAngle": "CBC documented Ville-Émard commercial rent pressure parallel to Verdun; QS proposed commercial lease register — merchants need tools now regardless of legislation.",
        "whyNow": "Station W closure ripple; borough mayors calling for entrepreneur support programs.",
        "persona": {"name": "Monk Blvd / Ville-Émard independent retailer", "borough": "Le Sud-Ouest", "language": "fr", "estimatedCount": 120, "countSource": "[hypothesis] SDC Monk merchant count"},
        "competitors": [{"name": "Commercial lawyers", "montrealPresence": "strong", "notes": "Expensive; used only after crisis."}],
        "mvpScope": {
            "coreJob": "Guided workbook: lease extraction, comp research, negotiation script",
            "mustHave": ["Lease key-date extractor (manual form)", "Negotiation script templates FR", "Decision matrix PDF", "Stripe $49", "Email course drip"],
            "wontHave": ["Legal review", "Automated comp database"],
            "stack": ["Next.js", "Stripe", "Resend"],
            "buildDays": 5,
            "conciergeFallback": "PDF workbook sold directly",
        },
        "businessModel": {"pricingCAD": "$49 workbook; $149 with 30-min review call", "firstCustomer": "SDC Monk merchant referral", "revenue60Day": {"low": 800, "high": 3500}},
        "gtm": {"firstTenCustomers": ["SDC Monk", "Verdun/Wellington cross-referral", "QS commercial lease newsjacking"], "channels": ["SDC", "Content marketing"]},
        "assumptions": [{"statement": "Merchants buy $49 workbook pre-renewal", "confidence": "hypothesis", "testMethod": "SDC lunch-and-learn pre-sell"}],
        "sources": [
            src("https://www.cbc.ca/news/canada/montreal/ville-emard-commercial-rent-increases-1.7490193", "CBC Ville-Émard commercial rent", "B", "pain-verified"),
            src("https://montrealgazette.com/news/verdun-station-w-closing-rent-hike/", "Gazette Station W rent reform calls", "B", "pain-verified"),
        ],
        "gates": gates("Montreal commercial rent pain without TAL protection.", "Workbook + email = 5 days.", "15-40 sales at $49.", "Digital + optional call.", "Not legal advice."),
        "status": "collected",
    },
    {
        "id": "pme-digital-micro-audit",
        "title": "PME Digital Micro-Audit",
        "tagline": "Lightweight digital readiness report for Montreal SMBs — ESSOR-adjacent but sized for sub-$2.5M shops.",
        "category": "b2b-micro-saas",
        "jtbd": {
            "situation": "When a 15-person Rosemont shop needs digital tools but can't afford Big-4 ESSOR diagnostic",
            "persona": "Owner of family manufacturing shop in Rosemont",
            "motivation": "identify 3 high-ROI digital fixes before hiring integrator",
            "outcome": "justify PME MTL loan or consultant spend with structured report",
            "statement": "When modernizing ops, a Rosemont shop owner wants a micro digital audit so they prioritize the right $5K investments.",
        },
        "montrealAngle": "ESSOR 1B requires $2.5M revenue — excludes most Montreal SMBs (72% have <10 employees). PME MTL pushes digital transformation but lacks lightweight self-serve entry.",
        "whyNow": "ESSOR Volet 1 open through Mar 2027 signals government priority; gap below revenue threshold.",
        "persona": {"name": "10-30 employee Montreal Island SMB owner", "borough": "Rosemont-La Petite-Patrie", "language": "fr", "estimatedCount": 5000, "countSource": "Statistique Québec — 72% employer firms have 1-9 employees; audit targets 10-30 subset"},
        "competitors": [{"name": "ESSOR-funded consultants", "url": "https://www.investquebec.com/", "montrealPresence": "strong", "notes": "Requires $2.5M revenue; $10-20K engagements."}, {"name": "PME MTL free advisory", "url": "https://pmemtl.com/en", "montrealPresence": "strong", "notes": "Free but human-scheduled; not instant."}],
        "mvpScope": {
            "coreJob": "20-question diagnostic producing prioritized digital action PDF",
            "mustHave": ["Industry-tuned questionnaire FR", "Priority matrix output", "PME MTL resource links", "Stripe $199 report", "Optional Cal.com review"],
            "wontHave": ["ESSOR application filing", "ERP implementation"],
            "stack": ["Next.js", "Supabase", "React-PDF", "Stripe", "Cal.com"],
            "buildDays": 7,
            "conciergeFallback": "Manual report delivery via Notion",
        },
        "businessModel": {"pricingCAD": "$199 self-serve; $499 with 1hr review", "firstCustomer": "PME MTL Est-de-l'Île advisor referral", "revenue60Day": {"low": 2000, "high": 8000}},
        "gtm": {"firstTenCustomers": ["PME MTL 6 centres", "Mallette/eclaireur consultant overflow", "LinkedIn FR PME ads"], "channels": ["PME MTL", "Consultant partners"]},
        "assumptions": [{"statement": "Sub-ESSOR SMBs pay $199 for structured diagnostic", "confidence": "hypothesis", "testMethod": "PME MTL advisor validates with 5 clients"}],
        "sources": [
            src("https://grantcompass.ca/grants/essor-program-component-1-grants", "ESSOR Component 1 eligibility", "B", "grant-tailwind", "Requires $2.5M revenue for 1B/1C."),
            src("https://pmemtl.com/en", "PME MTL advisory mandate", "A", "grant-tailwind"),
            src("https://statistique.quebec.ca/fr/document/nombre-entreprises-actives-quebec", "Statistique Québec active businesses", "A", "pain-verified"),
        ],
        "gates": gates("ESSOR gap specifically hurts Montreal SMBs below revenue threshold.", "Questionnaire + PDF = 7 days.", "10-20 reports at $199.", "Optional review calls scoped.", "Advisory not ESSOR-certified diagnostic."),
        "status": "collected",
    },
    {
        "id": "student-july1-move-kit",
        "title": "Student July 1 Move Kit",
        "tagline": "McGill/Concordia student move-in checklist for Montreal lease transfers and borough rules.",
        "category": "consumer",
        "jtbd": {
            "situation": "When international student arrives for September but sublet chain ends June 30",
            "persona": "Concordia international student navigating July 1 sublet gap",
            "motivation": "find short-term storage and understand lease transfer rules",
            "outcome": "avoid homelessness between sublet and fall lease",
            "statement": "When caught in July 1 housing gap, a Concordia student wants a move kit so they find storage and temp housing.",
        },
        "montrealAngle": "McGill/Concordia drive fall demand; July 1 mass move + 1.8% vacancy; Parc-Extension tenants facing 16% rent hikes staying put.",
        "whyNow": "May 2026 SARL campaign; student lease cycle peaks June-July.",
        "persona": {"name": "International or out-of-province student renter", "borough": "CDN-NDG / Ville-Marie", "language": "en", "estimatedCount": 40000, "countSource": "[hypothesis] McGill+Concordia enrollment with off-campus housing"},
        "competitors": [{"name": "University housing offices", "montrealPresence": "strong", "notes": "Fall-focused; weak on July 1 gap."}, {"name": "Québec.ca SARL", "url": "https://www.quebec.ca/", "montrealPresence": "strong", "notes": "Emergency; not student-specific planner."}],
        "mvpScope": {
            "coreJob": "Student-specific July 1 timeline with storage/short-term rental links",
            "mustHave": ["Student move checklist EN/FR", "Storage affiliate links", "Borough parking permit notes", "Stripe $9.99", "WhatsApp share card"],
            "wontHave": ["Apartment search marketplace", "Lease legal review"],
            "stack": ["Next.js", "Stripe"],
            "buildDays": 4,
            "conciergeFallback": "PDF guide via Gumroad",
        },
        "businessModel": {"pricingCAD": "$9.99 guide + affiliate revenue", "firstCustomer": "Concordia student Facebook group ad", "revenue60Day": {"low": 500, "high": 3000}},
        "gtm": {"firstTenCustomers": ["McGill/Concordia FB groups", "International student orientation partners", "June Google ads"], "channels": ["Facebook", "Campus groups"]},
        "assumptions": [{"statement": "Students pay $10 for move survival guide", "confidence": "hypothesis", "testMethod": "Campus group free preview"}],
        "sources": [
            src("https://www.cbc.ca/news/canada/montreal/quebec-moving-day-housing-1.7573206", "CBC moving day housing", "B", "pain-verified"),
            src("https://montreal.citynews.ca/2025/07/01/quebecs-moving-day/", "CityNews Parc-Ex rent pressure", "B", "pain-verified", "Tenants staying due to 16% hikes."),
            src("https://www.newswire.ca/fr/news-releases/a-l-approche-du-1er-juillet-les-services-d-aide-a-la-recherche-de-logement-845732592.html", "SHQ SARL 2026 campaign", "B", "seasonal"),
        ],
        "gates": gates("Quebec July 1 + Montreal student housing cluster.", "Static guide = 4 days.", "May-July ad spike.", "Fully automated.", "Info product only."),
        "status": "collected",
    },
    {
        "id": "grand-prix-hospitality-staff-pool",
        "title": "Grand Prix Hospitality Staff Pool",
        "tagline": "Pre-vetted part-time server pool for Montreal F1 weekend restaurant surge staffing.",
        "category": "hospitality-tourism",
        "jtbd": {
            "situation": "When Grand Prix weekend triples covers but TFW cap limits core staff",
            "persona": "Manager at Crescent St bar facing F1 weekend rush",
            "motivation": "access pre-screened bilingual servers for 4-day surge",
            "outcome": "maximize F1 revenue without service collapse",
            "statement": "When F1 weekend hits, a Crescent St manager wants a vetted server pool so they handle the surge.",
        },
        "montrealAngle": "Grand Prix + Jazz Fest + terrace season stack June; Crescent/Latin Quarter F&B epicenter; staffing crisis makes seasonal surge acute.",
        "whyNow": "F1 2026 June 5-7; restaurants already cutting weekday hours due to labour shortage.",
        "persona": {"name": "Bar-restaurant manager, tourist corridor", "borough": "Ville-Marie", "language": "bilingual", "estimatedCount": 150, "countSource": "[hypothesis] downtown tourist-corridor restaurants"},
        "competitors": [{"name": "Agence de placement hospitality", "montrealPresence": "strong", "notes": "15-25% markup; slow for 4-day surge."}, {"name": "Instagram hiring posts", "montrealPresence": "strong", "notes": "Ad hoc; no vetting."}],
        "mvpScope": {
            "coreJob": "Managers post F1 shifts; vetted pool accepts via SMS",
            "mustHave": ["Server profile signup", "Manager shift post", "SMS notify", "Stripe placement fee", "Bilingual profiles"],
            "wontHave": ["Full HR/payroll", "Work permit verification automation"],
            "stack": ["Next.js", "Supabase", "Twilio", "Stripe"],
            "buildDays": 7,
            "conciergeFallback": "Manual spreadsheet matching for $50/placement",
        },
        "businessModel": {"pricingCAD": "$50-75/placement or $299 F1 weekend package", "firstCustomer": "Crescent St restaurant via ARQ", "revenue60Day": {"low": 1500, "high": 6000}},
        "gtm": {"firstTenCustomers": ["ARQ pre-F1 outreach", "Hospitality school job boards", "Crescent St BIA [hypothesis]"], "channels": ["ARQ", "Schools", "Direct"]},
        "assumptions": [{"statement": "Managers pay premium for pre-vetted F1 staff", "confidence": "hypothesis", "testMethod": "5 manager pre-commitments by May 15"}],
        "sources": [
            src("https://montreal.citynews.ca/2025/10/05/quebec-restaurants-immigration-worker-cap/", "CityNews restaurant labour crisis", "B", "pain-verified"),
            src("https://www.newswire.ca/news-releases/more-than-17-000-international-business-tourists-expected-at-the-palais-des-congres-de-montreal-this-summer-803199751.html", "Newswire summer tourism surge", "B", "seasonal"),
        ],
        "gates": gates("Montreal June event stacking unique; Crescent corridor specific.", "Signup + SMS matching = 7 days.", "20-40 placements at $50+.", "Seasonal burst; concierge OK.", "Not employment agency — intro platform with disclaimer [verify RBQ/normes travail]."),
        "status": "collected",
    },
]

for idea in IDEAS:
    idea["frameworkVersion"] = FW
    idea["collectedAt"] = COLLECTED_AT
    (OUT / f"{idea['id']}.json").write_text(json.dumps(idea, indent=2, ensure_ascii=False) + "\n")
    print(idea["id"])
